In [1]:
import pandas as pd
import numpy as np

# DataFrame Basics

Hi there!

Can you read in the transactions dataset and report on:

* The number of rows and columns
* The names of the columns
* The datatypes of each column

In [2]:
transactions = pd.read_csv('transactions.csv')

transactions

             date  store_nbr  transactions
0      2013-01-01         25           770
1      2013-01-02          1          2111
2      2013-01-02          2          2358
3      2013-01-02          3          3487
4      2013-01-02          4          1922
...           ...        ...           ...
83483  2017-08-15         50          2804
83484  2017-08-15         51          1573
83485  2017-08-15         52          2255
83486  2017-08-15         53           932
83487  2017-08-15         54           802

[83488 rows x 3 columns]

In [3]:
transactions.shape

(83488, 3)

In [4]:
transactions.dtypes

date            object
store_nbr        int64
transactions     int64
dtype: object

In [5]:
transactions.index.max()

83487

# Exploring DataFrames

Hello!

* Can you quickly inspect the first 5 rows of the transactions data? 

* Then, dive a bit more deeply into the data and check if there are any missing values.
* What about the number of unique dates? I want to make sure we didn’t leave any out.
* Finally, can you report the mean, median, min and max of “transactions”?  I want to check for any anomalies in our data.

In [6]:
transactions.head()

         date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922

In [7]:
transactions.isna().sum()

transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          83488 non-null  object
 1   store_nbr     83488 non-null  int64
 2   transactions  83488 non-null  int64
dtypes: int64(2), object(1)
memory usage: 1.9+ MB

In [8]:
transactions.describe(include='all')

              date     store_nbr  transactions
count        83488  83488.000000  83488.000000
unique        1682           NaN           NaN
top     2017-07-29           NaN           NaN
freq            54           NaN           NaN
mean           NaN     26.939237   1694.602158
std            NaN     15.608204    963.286644
min            NaN      1.000000      5.000000
25%            NaN     13.000000   1046.000000
50%            NaN     27.000000   1393.000000
75%            NaN     40.000000   2079.000000
max            NaN     54.000000   8359.000000

# Accessing DataFrames

Hi, starting to dive deeper into this data.

I noticed that the first row is the only one from 2013-01-01.

* Can you get me a copy of the DataFrame that excludes that row, and only includes “store_nbr” and “transactions”?
* Also, can you report the number of unique store numbers?
* Finally, return the total number of transactions in millions

In [9]:
transactions.head()

         date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922

In [10]:
transactions.loc[1:, 'store_nbr':'transactions']

       store_nbr  transactions
1              1          2111
2              2          2358
3              3          3487
4              4          1922
5              5          1903
...          ...           ...
83483         50          2804
83484         51          1573
83485         52          2255
83486         53           932
83487         54           802

[83487 rows x 2 columns]

In [11]:
transactions.loc[:,'store_nbr'].nunique()

54

In [12]:
transactions.loc[:,'transactions'].sum() / 1000000

np.float64(141.478945)

# Dropping Data and Duplicates

Hi there!

Can you:

 
1. Drop the date column but not in place
2. Return a dataframe that only includes the last row for each of the stores.

Thanks!

In [13]:
transactions.head()

         date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922

In [14]:
transactions.drop('date', axis=1)

       store_nbr  transactions
0             25           770
1              1          2111
2              2          2358
3              3          3487
4              4          1922
...          ...           ...
83483         50          2804
83484         51          1573
83485         52          2255
83486         53           932
83487         54           802

[83488 rows x 2 columns]

In [15]:
transactions.drop_duplicates(subset='store_nbr', keep='last').head()

             date  store_nbr  transactions
83434  2017-08-15          1          1693
83435  2017-08-15          2          1737
83436  2017-08-15          3          2956
83437  2017-08-15          4          1283
83438  2017-08-15          5          1310

# Missing Data

Hello, 

Can you tell if any dates or prices are missing in the oil dataset?

Then compare the mean of the oil series when filling in with mean vs. filling in with 0.

Thanks!

In [16]:
oil = pd.read_csv("oil.csv")

oil

            date  dcoilwtico
0     2013-01-01         NaN
1     2013-01-02       93.14
2     2013-01-03       92.97
3     2013-01-04       93.12
4     2013-01-07       93.20
...          ...         ...
1213  2017-08-25       47.65
1214  2017-08-28       46.40
1215  2017-08-29       46.46
1216  2017-08-30       45.96
1217  2017-08-31       47.26

[1218 rows x 2 columns]

In [17]:
oil.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1218 non-null   object
 1   dcoilwtico  1175 non-null   float64
dtypes: float64(1), object(1)
memory usage: 19.2+ KB

In [18]:
oil.isna().sum()

date           0
dcoilwtico    43
dtype: int64

In [19]:
oil.loc[:, 'dcoilwtico'].fillna(0).mean()

np.float64(65.32379310344828)

In [20]:
oil.loc[:, 'dcoilwtico'].fillna(oil.loc[:, 'dcoilwtico']).mean()

np.float64(67.71436595744682)

# Filtering DataFrames

I need some quick research on store 25:

* First, calculate the percentage of times ALL stores had more than 2000 transactions
* Then, calculate the percentage of times store 25 had more than 2000 transactions, and calculate the sum of transactions on these days
* Finally, sum the transactions for stores 25 and 31, that occurred in May or June, and had less than 2000 transactions

In [21]:
transactions.head()

         date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922

In [22]:
transactions.query("date.str[6] == '1'")

             date  store_nbr  transactions
0      2013-01-01         25           770
1      2013-01-02          1          2111
2      2013-01-02          2          2358
3      2013-01-02          3          3487
4      2013-01-02          4          1922
...           ...        ...           ...
72977  2017-01-31         49          2680
72978  2017-01-31         50          2158
72979  2017-01-31         51          1448
72980  2017-01-31         53           950
72981  2017-01-31         54           793

[13301 rows x 3 columns]

In [23]:
(transactions['transactions'] > 2000).mean()

np.float64(0.26680481027213493)

In [24]:
mask = (transactions['store_nbr'] == 25) & (transactions['transactions'] > 2000)

(transactions.loc[mask].count() / 
 transactions.loc[transactions['store_nbr'] == 25].count()
).iloc[2]

np.float64(0.0346749226006192)

In [25]:
transactions[mask].loc[:, 'transactions'].sum()

np.int64(144903)

In [26]:
transactions.query (
    'store_nbr in [25, 31] & date.str[6] in ["5", "6"] & transactions < 2000'
).transactions.sum()

np.int64(644910)

# Sorting DataFrames

Hi there,
* Can you get me a dataset that includes the 5 days with the highest transactions counts? Any similarities between them?
* Then, can you get me a dataset sorted by date from earliest to most recent, but with the highest transactions first and the lowest transactions last for each day?
* Finally, sort the columns in reverse alphabetical order. 

Thanks!

In [27]:
transactions.head()

         date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922

In [28]:
transactions.sort_values(by=['transactions'], ascending=False).iloc[:5,:]

             date  store_nbr  transactions
52011  2015-12-23         44          8359
71010  2016-12-23         44          8307
16570  2013-12-23         44          8256
33700  2014-12-23         44          8120
16572  2013-12-23         46          8001

In [29]:
transactions.sort_values(by=['date', 'transactions'], ascending=[True, False])

             date  store_nbr  transactions
0      2013-01-01         25           770
40     2013-01-02         46          4886
38     2013-01-02         44          4821
39     2013-01-02         45          4208
41     2013-01-02         47          4161
...           ...        ...           ...
83455  2017-08-15         22           766
83449  2017-08-15         16           742
83465  2017-08-15         32           615
83468  2017-08-15         35           612
83459  2017-08-15         26           534

[83488 rows x 3 columns]

In [30]:
transactions.sort_index(axis=1, ascending=False)

       transactions  store_nbr        date
0               770         25  2013-01-01
1              2111          1  2013-01-02
2              2358          2  2013-01-02
3              3487          3  2013-01-02
4              1922          4  2013-01-02
...             ...        ...         ...
83483          2804         50  2017-08-15
83484          1573         51  2017-08-15
83485          2255         52  2017-08-15
83486           932         53  2017-08-15
83487           802         54  2017-08-15

[83488 rows x 3 columns]